--CREATE TABLE Roles(
--RoleId UNIQUEIDENTIFIER PRIMARY KEY,
--NAME NVARCHAR(100) UNIQUE NOT NULL
--);


--ALTER TABLE Users
--ADD RoleId UNIQUEIDENTIFIER NULL;

--ALTER TABLE Users
--ADD CONSTRAINT FK_Users_Roles
--FOREIGN KEY (RoleId) REFERENCES Roles(RoleId);